version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    command: python admin_panel/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: apdb_devel
      POSTGRES_USER: ap_admin
      POSTGRES_PASSWORD: ap_pass1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
