version: '3.9'

services:
  web:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/project
      - pgsocket:/var/run/postgresql/
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ap_devel
      POSTGRES_USER: ap_admin
      POSTGRES_PASSWORD: ap_pass1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgsocket:/var/run/postgresql/

volumes:
  pgdata:
  pgsocket:
